[build]
  command = "npm run build"
  publish = "dist"

# API proxyk (ugyanaz mint Vite proxy)
[[redirects]]
  from = "/users/*"
  to = "https://nodejs303.dszcbaross.edu.hu/users/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/game/*"
  to = "https://nodejs303.dszcbaross.edu.hu/api/game/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/admin/*"
  to = "https://nodejs303.dszcbaross.edu.hu/api/admin/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/card_img/*"
  to = "https://nodejs303.dszcbaross.edu.hu/card_img/:splat"
  status = 200
  force = true

# SPA redirect (React routinghoz)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200